<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Registro_de_Empleados_Servicios</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Registro de Empleados.Modelos\Registro de Empleados_Modelos.csproj" />
  </ItemGroup>

</Project>
